# Attendance Data Cleaning & Preparation

This notebook performs data inspection, duplicate removal, status standardization,
date transformation, missing value treatment, and working-hours validation.

In [1]:
# Import Pandas

import pandas as pd

In [2]:
# load dataset

df = pd.read_csv("Employee_MIS_Dataset/performance.csv")
df

,Performance_ID,Employee_ID,Review_Month,Performance_Score,Productivity_Score,Manager_Rating
0,1,1001,2025-01-01,5.9,95.1,5.9
1,2,1001,2025-02-01,7.5,81.5,7.6
2,3,1001,2025-03-01,8.7,73.9,9.5
3,4,1001,2025-04-01,8.1,65.2,8.7
4,5,1001,2025-05-01,6.4,58.4,5.6
...,...,...,...,...,...,...
5998,5999,1500,2025-11-01,4.4,52.3,4.5
5999,6000,1500,2025-12-01,6.0,82.8,5.8
6000,6,1001,2025-06-01,7.0,72.5,7.7
6001,106,1009,2025-10-01,7.6,76.7,7.4
6002,1006,1084,2025-10-01,NaN,67.6,8.1

In [3]:
# Top 5 rows

df.head()

,Performance_ID,Employee_ID,Review_Month,Performance_Score,Productivity_Score,Manager_Rating
0,1,1001,2025-01-01,5.9,95.1,5.9
1,2,1001,2025-02-01,7.5,81.5,7.6
2,3,1001,2025-03-01,8.7,73.9,9.5
3,4,1001,2025-04-01,8.1,65.2,8.7
4,5,1001,2025-05-01,6.4,58.4,5.6

In [4]:
# Top 10 rows

df.head(10)

,Performance_ID,Employee_ID,Review_Month,Performance_Score,Productivity_Score,Manager_Rating
0,1,1001,2025-01-01,5.9,95.1,5.9
1,2,1001,2025-02-01,7.5,81.5,7.6
2,3,1001,2025-03-01,8.7,73.9,9.5
3,4,1001,2025-04-01,8.1,65.2,8.7
4,5,1001,2025-05-01,6.4,58.4,5.6
5,6,1001,2025-06-01,7.0,72.5,7.7
6,7,1001,2025-07-01,6.1,66.0,6.9
7,8,1001,2025-08-01,7.1,59.9,8.6
8,9,1001,2025-09-01,5.9,75.1,5.2
9,10,1001,2025-10-01,7.2,30.0,8.6

In [5]:
# Dataset shape

df.shape

(6003, 6)

In [7]:
df.columns

Index(['Performance_ID', 'Employee_ID', 'Review_Month', 'Performance_Score',
       'Productivity_Score', 'Manager_Rating'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6003 entries, 0 to 6002
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Performance_ID      6003 non-null   int64
 1   Employee_ID         6003 non-null   int64
 2   Review_Month        6003 non-null   str
 3   Performance_Score   5962 non-null   float64
 4   Productivity_Score  6003 non-null   float64
 5   Manager_Rating      6003 non-null   float64
dtypes: float64(3), int64(2), str(1)
memory usage: 281.5 KB

In [9]:
df.describe()

,Performance_ID,Employee_ID,Performance_Score,Productivity_Score,Manager_Rating
count,6003.000000,6003.000000,5962.000000,6003.000000,6003.000000
mean,2999.186740,1250.390471,7.184921,75.148376,7.176845
std,1732.787121,144.398765,1.377309,14.505762,1.631580
min,1.000000,1001.000000,2.400000,30.000000,1.000000
25%,1498.500000,1125.000000,6.200000,65.450000,6.100000
50%,2999.000000,1250.000000,7.200000,75.300000,7.200000
75%,4499.500000,1375.000000,8.100000,85.100000,8.400000
max,6000.000000,1500.000000,10.000000,150.000000,10.000000

In [10]:
# Missing value

In [11]:
df.isnull().sum()

Performance_ID         0
Employee_ID            0
Review_Month           0
Performance_Score     41
Productivity_Score     0
Manager_Rating         0
dtype: int64

In [12]:
(df.isnull().sum() / len(df)) * 100

Performance_ID        0.000000
Employee_ID           0.000000
Review_Month          0.000000
Performance_Score     0.682992
Productivity_Score    0.000000
Manager_Rating        0.000000
dtype: float64

In [13]:
missing = df.isnull().sum()
missing[missing > 0]

Performance_Score    41
dtype: int64

In [14]:
df[df.isnull().any(axis = 1)]

,Performance_ID,Employee_ID,Review_Month,Performance_Score,Productivity_Score,Manager_Rating
11,12,1001,2025-12-01,NaN,97.8,9.6
175,176,1015,2025-08-01,NaN,93.8,7.1
287,288,1024,2025-12-01,NaN,75.1,5.3
380,381,1032,2025-09-01,NaN,88.3,9.7
388,389,1033,2025-05-01,NaN,52.9,8.6
604,605,1051,2025-05-01,NaN,75.1,8.5
610,611,1051,2025-11-01,NaN,87.8,5.7
693,694,1058,2025-10-01,NaN,92.7,6.6
694,695,1058,2025-11-01,NaN,85.9,8.5
981,982,1082,2025-10-01,NaN,61.0,6.8
996,997,1084,2025-01-01,NaN,64.9,6.9
1005,1006,1084,2025-10-01,NaN,67.6,8.1
1215,1216,1102,2025-04-01,NaN,95.7,9.0
1481,1482,1124,2025-06-01,NaN,87.8,10.0
1582,1583,1132,2025-11-01,NaN,59.1,7.9
1592,1593,1133,2025-09-01,NaN,99.6,4.8
1661,1662,1139,2025-06-01,NaN,58.7,5.5
1977,1978,1165,2025-10-01,NaN,93.3,5.2
2622,2623,1219,2025-07-01,NaN,96.3,4.6
2753,2754,1230,2025-06-01,NaN,89.2,6.0
2891,2892,1241,2025-12-01,NaN,86.9,6.2
2919,2920,1244,2025-04-01,NaN,73.0,8.6
3061,3062,1256,2025-02-01,NaN,89.7,8.7
3996,3997,1334,2025-01-01,NaN,90.9,10.0
4025,4026,1336,2025-06-01,NaN,79.2,4.2
4062,4063,1339,2025-07-01,NaN,56.7,10.0
4121,4122,1344,2025-06-01,NaN,92.1,4.1
4159,4160,1347,2025-08-01,NaN,79.0,9.5
4506,4507,1376,2025-07-01,NaN,80.0,4.6
4548,4549,1380,2025-01-01,NaN,66.1,7.5
4598,4599,1384,2025-03-01,NaN,46.4,5.0
4724,4725,1394,2025-09-01,NaN,63.7,6.6
4964,4965,1414,2025-09-01,NaN,51.2,4.2
5132,5133,1428,2025-09-01,NaN,85.8,10.0
5256,5257,1439,2025-01-01,NaN,87.1,7.2
5283,5284,1441,2025-04-01,NaN,92.0,8.8
5444,5445,1454,2025-09-01,NaN,100.0,6.7
5630,5631,1470,2025-03-01,NaN,54.5,7.1
5707,5708,1476,2025-08-01,NaN,93.2,5.3
5770,5771,1481,2025-11-01,NaN,72.0,5.8
6002,1006,1084,2025-10-01,NaN,67.6,8.1

In [15]:
# Duplicates

In [17]:
print(df.duplicated().sum())

3

In [18]:
df[df.duplicated()]

,Performance_ID,Employee_ID,Review_Month,Performance_Score,Productivity_Score,Manager_Rating
6000,6,1001,2025-06-01,7.0,72.5,7.7
6001,106,1009,2025-10-01,7.6,76.7,7.4
6002,1006,1084,2025-10-01,NaN,67.6,8.1

In [19]:
df = df.drop_duplicates()

In [20]:
print(df.duplicated().sum())

0

In [21]:
# Review Month

In [22]:
print(df["Review_Month"].dtype)

str

In [23]:
df["Review_Month"] = pd.to_datetime(df["Review_Month"])

In [24]:
print(df["Review_Month"].dtype)

datetime64[us]

In [25]:
df["Review_Year"] = df["Review_Month"].dt.year

In [26]:
df["Review_Month_Number"] = df["Review_Month"].dt.month

In [27]:
df["Review_Month_Name"] = df["Review_Month"].dt.month_name()

In [29]:
df[[
    "Review_Month",
    "Review_Year",
    "Review_Month_Number",
    "Review_Month_Name"
]].head()

  Review_Month  Review_Year  Review_Month_Number Review_Month_Name
0   2025-01-01         2025                    1           January
1   2025-02-01         2025                    2          February
2   2025-03-01         2025                    3             March
3   2025-04-01         2025                    4             April
4   2025-05-01         2025                    5               May

In [30]:
# Performance score

In [31]:
df["Performance_Score"].describe()

count    5960.000000
mean        7.184883
std         1.377527
min         2.400000
25%         6.200000
50%         7.200000
75%         8.100000
max        10.000000
Name: Performance_Score, dtype: float64

In [33]:
print(df["Performance_Score"].isnull().sum())

40

In [36]:
print(df["Performance_Score"].median())

7.2

In [37]:
performance_median = df["Performance_Score"].median()

In [38]:
df["Performance_Score"] = df["Performance_Score"].fillna(performance_median)

In [39]:
df.isnull().sum()

Performance_ID         0
Employee_ID            0
Review_Month           0
Performance_Score      0
Productivity_Score     0
Manager_Rating         0
Review_Year            0
Review_Month_Number    0
Review_Month_Name      0
dtype: int64

In [40]:
# Productivity score

In [41]:
df["Productivity_Score"].describe()

count    6000.000000
mean       75.149817
std        14.509007
min        30.000000
25%        65.400000
50%        75.300000
75%        85.125000
max       150.000000
Name: Productivity_Score, dtype: float64

In [43]:
df[
    (df["Productivity_Score"] < 0) |
    (df["Productivity_Score"] > 100) 
]

,Performance_ID,Employee_ID,Review_Month,Performance_Score,Productivity_Score,Manager_Rating,Review_Year,Review_Month_Number,Review_Month_Name
179,180,1015,2025-12-01,5.5,150.0,5.2,2025,12,December
905,906,1076,2025-06-01,7.7,150.0,8.5,2025,6,June
1042,1043,1087,2025-11-01,8.0,150.0,8.0,2025,11,November
1137,1138,1095,2025-10-01,7.4,150.0,8.2,2025,10,October
1169,1170,1098,2025-06-01,6.3,150.0,5.0,2025,6,June
1178,1179,1099,2025-03-01,7.0,150.0,6.9,2025,3,March
1909,1910,1160,2025-02-01,6.6,150.0,6.7,2025,2,February
2043,2044,1171,2025-04-01,6.8,150.0,6.3,2025,4,April
2352,2353,1197,2025-01-01,5.6,150.0,6.4,2025,1,January
2604,2605,1218,2025-01-01,8.0,150.0,7.7,2025,1,January
3002,3003,1251,2025-03-01,5.0,150.0,3.2,2025,3,March
3255,3256,1272,2025-04-01,7.0,150.0,8.4,2025,4,April
3279,3280,1274,2025-04-01,7.3,150.0,8.5,2025,4,April
3346,3347,1279,2025-11-01,8.4,150.0,9.1,2025,11,November
3675,3676,1307,2025-04-01,8.2,150.0,9.2,2025,4,April
4290,4291,1358,2025-07-01,6.7,150.0,7.4,2025,7,July
4320,4321,1361,2025-01-01,7.7,150.0,7.8,2025,1,January
4449,4450,1371,2025-10-01,6.2,150.0,5.3,2025,10,October
5461,5462,1456,2025-02-01,7.3,150.0,6.6,2025,2,February
5559,5560,1464,2025-04-01,8.3,150.0,10.0,2025,4,April

In [44]:
df.loc[
    (df["Productivity_Score"] < 0) |
    (df["Productivity_Score"] > 100),
    "Productivity_Score"
] = pd.NA

In [50]:
print(df["Productivity_Score"].isnull().sum())

0

In [51]:
productivity_median = df["Productivity_Score"].median()

In [52]:
df["Productivity_Score"] = df["Productivity_Score"].fillna(productivity_median)

In [53]:
print(df["Productivity_Score"].isnull().sum())

0

In [54]:
# Manager rating

In [55]:
df["Manager_Rating"].describe()

count    6000.000000
mean        7.176567
std         1.631928
min         1.000000
25%         6.100000
50%         7.200000
75%         8.400000
max        10.000000
Name: Manager_Rating, dtype: float64

In [56]:
df[
    (df["Manager_Rating"] < 1) |
    (df["Manager_Rating"] > 10)
]

Empty DataFrame
Columns: [Performance_ID, Employee_ID, Review_Month, Performance_Score, Productivity_Score, Manager_Rating, Review_Year, Review_Month_Number, Review_Month_Name]
Index: []

In [58]:
print(df["Manager_Rating"].isnull().sum())

0

In [59]:
df.isnull().sum()

Performance_ID         0
Employee_ID            0
Review_Month           0
Performance_Score      0
Productivity_Score     0
Manager_Rating         0
Review_Year            0
Review_Month_Number    0
Review_Month_Name      0
dtype: int64

In [60]:
df.duplicated().sum()

np.int64(0)

In [61]:
df.dtypes

Performance_ID                  int64
Employee_ID                     int64
Review_Month           datetime64[us]
Performance_Score             float64
Productivity_Score            float64
Manager_Rating                float64
Review_Year                     int32
Review_Month_Number             int32
Review_Month_Name                 str
dtype: object

In [62]:
df.shape

(6000, 9)

In [63]:
df.head()

,Performance_ID,Employee_ID,Review_Month,Performance_Score,Productivity_Score,Manager_Rating,Review_Year,Review_Month_Number,Review_Month_Name
0,1,1001,2025-01-01,5.9,95.1,5.9,2025,1,January
1,2,1001,2025-02-01,7.5,81.5,7.6,2025,2,February
2,3,1001,2025-03-01,8.7,73.9,9.5,2025,3,March
3,4,1001,2025-04-01,8.1,65.2,8.7,2025,4,April
4,5,1001,2025-05-01,6.4,58.4,5.6,2025,5,May

In [64]:
# Save file

df.to_csv(
    "performance_cleaned.csv",
    index=False
)

In [65]:
pd.read_csv("performance_cleaned.csv").head()

,Performance_ID,Employee_ID,Review_Month,Performance_Score,Productivity_Score,Manager_Rating,Review_Year,Review_Month_Number,Review_Month_Name
0,1,1001,2025-01-01,5.9,95.1,5.9,2025,1,January
1,2,1001,2025-02-01,7.5,81.5,7.6,2025,2,February
2,3,1001,2025-03-01,8.7,73.9,9.5,2025,3,March
3,4,1001,2025-04-01,8.1,65.2,8.7,2025,4,April
4,5,1001,2025-05-01,6.4,58.4,5.6,2025,5,May