# Leave Data Cleaning & Preparation

This notebook performs data inspection, duplicate removal, missing value handling,
status standardization, date transformation, and leave data validation.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Employee_MIS_Dataset/leaves.csv")

In [3]:
df

,Leave_ID,Employee_ID,Leave_Date,Leave_Type,Leave_Days,Approval_Status
0,1,1006,2025-03-19,Casual Leave,3,Approved
1,2,1266,2025-03-18,Sick Leave,2,Approved
2,3,1157,2025-05-06,Earned Leave,3,Approved
3,4,1378,2025-10-03,Casual Leave,1,Pending
4,5,1044,2025-01-28,Sick Leave,1,Pending
...,...,...,...,...,...,...
4998,4999,1234,2025-02-20,Emergency Leave,1,Rejected
4999,5000,1080,2025-01-04,Emergency Leave,1,Approved
5000,11,1444,2025-01-16,Emergency Leave,1,Approved
5001,51,1092,2025-08-21,Earned Leave,1,Approved
5002,501,1017,2025-10-15,Emergency Leave,1,Approved

In [4]:
# Top q5 rows

df.head()

   Leave_ID  Employee_ID  Leave_Date    Leave_Type  Leave_Days Approval_Status
0         1         1006  2025-03-19  Casual Leave           3        Approved
1         2         1266  2025-03-18    Sick Leave           2        Approved
2         3         1157  2025-05-06  Earned Leave           3        Approved
3         4         1378  2025-10-03  Casual Leave           1         Pending
4         5         1044  2025-01-28    Sick Leave           1         Pending

In [6]:
# Top 10 rows

df.head(10)

,Leave_ID,Employee_ID,Leave_Date,Leave_Type,Leave_Days,Approval_Status
0,1,1006,2025-03-19,Casual Leave,3,Approved
1,2,1266,2025-03-18,Sick Leave,2,Approved
2,3,1157,2025-05-06,Earned Leave,3,Approved
3,4,1378,2025-10-03,Casual Leave,1,Pending
4,5,1044,2025-01-28,Sick Leave,1,Pending
5,6,1372,2025-11-05,Earned Leave,1,Approved
6,7,1186,2025-12-19,Emergency Leave,2,Approved
7,8,1200,2025-10-29,Casual Leave,1,Approved
8,9,1149,2025-09-21,Sick Leave,1,Approved
9,10,1094,2025-04-04,Sick Leave,1,Rejected

In [7]:
df.shape

(5003, 6)

In [8]:
df.describe()

          Leave_ID  Employee_ID   Leave_Days
count  5003.000000  5003.000000  5003.000000
mean   2499.113132  1250.196082     1.299620
std    1444.207798   144.926139     0.555203
min       1.000000  1001.000000     1.000000
25%    1248.500000  1121.000000     1.000000
50%    2499.000000  1251.000000     1.000000
75%    3749.500000  1375.000000     2.000000
max    5000.000000  1500.000000     3.000000

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5003 entries, 0 to 5002
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Leave_ID         5003 non-null   int64
 1   Employee_ID      5003 non-null   int64
 2   Leave_Date       5003 non-null   str
 3   Leave_Type       4978 non-null   str
 4   Leave_Days       5003 non-null   int64
 5   Approval_Status  5003 non-null   str
dtypes: int64(3), str(3)
memory usage: 234.6 KB

In [10]:
df.columns

Index(['Leave_ID', 'Employee_ID', 'Leave_Date', 'Leave_Type', 'Leave_Days',
       'Approval_Status'],
      dtype='str')

In [11]:
# Misssing values

In [12]:
df.isnull().sum()

Leave_ID            0
Employee_ID         0
Leave_Date          0
Leave_Type         25
Leave_Days          0
Approval_Status     0
dtype: int64

In [13]:
(df.isnull().sum() / len(df)) * 100

Leave_ID           0.0000
Employee_ID        0.0000
Leave_Date         0.0000
Leave_Type         0.4997
Leave_Days         0.0000
Approval_Status    0.0000
dtype: float64

In [14]:
missing = df.isnull().sum()
missing[missing > 0]

Leave_Type    25
dtype: int64

In [15]:
df[df.isnull().any(axis = 1)]

      Leave_ID  Employee_ID  Leave_Date Leave_Type  Leave_Days Approval_Status
91          92         1241  2025-11-01        NaN           2        Approved
553        554         1241  2025-04-19        NaN           1        Approved
618        619         1068  2025-06-28        NaN           1        Approved
715        716         1076  2025-12-03        NaN           1        Approved
853        854         1271  2025-01-05        NaN           1        Approved
966        967         1343  2025-06-30        NaN           1        Approved
1367      1368         1217  2025-09-10        NaN           2        Approved
1623      1624         1479  2025-04-06        NaN           1         Pending
1635      1636         1238  2025-03-01        NaN           1         Pending
2031      2032         1450  2025-11-21        NaN           1        Approved
2117      2118         1498  2025-06-18        NaN           1         Pending
2147      2148         1230  2025-03-14        NaN           1        Approved
2315      2316         1105  2025-07-01        NaN           3        Rejected
2726      2727         1170  2025-03-02        NaN           1        Approved
3103      3104         1115  2025-04-10        NaN           2        Approved
3419      3420         1219  2025-02-01        NaN           2        Rejected
3604      3605         1042  2025-06-25        NaN           1        Approved
3640      3641         1368  2025-06-25        NaN           2        Approved
3667      3668         1076  2025-04-20        NaN           1        Approved
3773      3774         1142  2025-05-17        NaN           1        Approved
3863      3864         1175  2025-03-06        NaN           1        Approved
4151      4152         1311  2025-09-14        NaN           1        Approved
4157      4158         1195  2025-01-15        NaN           1        Approved
4182      4183         1262  2025-03-22        NaN           2        Approved
4641      4642         1045  2025-11-05        NaN           2        Approved

In [16]:
# Duplicates

In [19]:
print(df.duplicated().sum())

3

In [20]:
df[df.duplicated()]

,Leave_ID,Employee_ID,Leave_Date,Leave_Type,Leave_Days,Approval_Status
5000,11,1444,2025-01-16,Emergency Leave,1,Approved
5001,51,1092,2025-08-21,Earned Leave,1,Approved
5002,501,1017,2025-10-15,Emergency Leave,1,Approved

In [21]:
df = df.drop_duplicates()

In [22]:
print(df.duplicated().sum())

0

In [23]:
# Leave type

In [24]:
df["Leave_Type"].unique()

<StringArray>
['Casual Leave', 'Sick Leave', 'Earned Leave', 'Emergency Leave', nan]
Length: 5, dtype: str

In [25]:
df["Leave_Type"].value_counts(dropna = False)

Leave_Type
Sick Leave         1272
Earned Leave       1245
Emergency Leave    1241
Casual Leave       1217
NaN                  25
Name: count, dtype: int64

In [26]:
df["Leave_Type"] = df["Leave_Type"].fillna("Unknown")

In [27]:
df["Leave_Type"].value_counts()

Leave_Type
Sick Leave         1272
Earned Leave       1245
Emergency Leave    1241
Casual Leave       1217
Unknown              25
Name: count, dtype: int64

In [28]:
# Approval status

In [30]:
df["Approval_Status"].unique()

<StringArray>
['Approved', 'Pending', 'Rejected']
Length: 3, dtype: str

In [31]:
df["Approval_Status"].value_counts()

Approval_Status
Approved    3927
Rejected     604
Pending      469
Name: count, dtype: int64

In [32]:
df["Approval_Status"] = df["Approval_Status"].str.strip()

In [33]:
# Leave Date

In [35]:
print(df["Leave_Date"].dtype)

str

In [36]:
df["Leave_Date"] = pd.to_datetime(df["Leave_Date"])

In [37]:
print(df["Leave_Date"].dtype)

datetime64[us]

In [38]:
# MIS Date columns

In [39]:
df["Leave_Year"] = df["Leave_Date"].dt.year

In [40]:
df["Leave_Month"] = df["Leave_Date"].dt.month

In [41]:
df["Leave_Month_Name"] = df["Leave_Date"].dt.month_name()

In [43]:
df[[
    "Leave_Date",
    "Leave_Year",
    "Leave_Month",
    "Leave_Month_Name"
]].head()

  Leave_Date  Leave_Year  Leave_Month Leave_Month_Name
0 2025-03-19        2025            3            March
1 2025-03-18        2025            3            March
2 2025-05-06        2025            5              May
3 2025-10-03        2025           10          October
4 2025-01-28        2025            1          January

In [44]:
# Leave days

In [45]:
df["Leave_Days"].describe()

count    5000.000000
mean        1.299800
std         0.555321
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max         3.000000
Name: Leave_Days, dtype: float64

In [46]:
df[df["Leave_Days"] <= 0]

Empty DataFrame
Columns: [Leave_ID, Employee_ID, Leave_Date, Leave_Type, Leave_Days, Approval_Status, Leave_Year, Leave_Month, Leave_Month_Name]
Index: []

In [47]:
# Final validation

In [48]:
df.isnull().sum()

Leave_ID            0
Employee_ID         0
Leave_Date          0
Leave_Type          0
Leave_Days          0
Approval_Status     0
Leave_Year          0
Leave_Month         0
Leave_Month_Name    0
dtype: int64

In [49]:
df.duplicated().sum()

np.int64(0)

In [50]:
df.to_csv(
    "leaves_cleaned.csv",
    index=False
)

In [51]:
pd.read_csv("leaves_cleaned.csv").head()

,Leave_ID,Employee_ID,Leave_Date,Leave_Type,Leave_Days,Approval_Status,Leave_Year,Leave_Month,Leave_Month_Name
0,1,1006,2025-03-19,Casual Leave,3,Approved,2025,3,March
1,2,1266,2025-03-18,Sick Leave,2,Approved,2025,3,March
2,3,1157,2025-05-06,Earned Leave,3,Approved,2025,5,May
3,4,1378,2025-10-03,Casual Leave,1,Pending,2025,10,October
4,5,1044,2025-01-28,Sick Leave,1,Pending,2025,1,January